#in class activity 9/20/22
install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
library(palmerpenguins)
class(penguins)
penguins = data.frame(penguins)
mean(penguins$body_mass_g)
head(penguins)
help("mean")
mean(penguins$body_mass_g, na.rm = TRUE)
summary(penguins)
boxplot(penguins$flipper_length_mm)
boxplot(flipper_length_mm ~ sex, data = penguins)
par(mfrow = c(1,2))
boxplot(penguins$flipper_length_mm)
boxplot(flipper_length_mm ~ sex, data = penguins)
coplot(body_mass_g ~ flipper_length_mm | species, data = penguins)
png(filename = here("basic_coplot.png"), width = 800, height = 600)
coplot(body_mass_g ~ flipper_length_mm | species, data = penguins)
dev.off()

require(here)
png(filename = here("basic_coplot.png"), width = 1000, height = 600)
coplot(body_mass_g ~ flipper_length_mm | species, data = penguins, rows = 1, 
       ylab = "Body Mass (g)", xlab = "Flipper Length (mm)")
dev.off()
